#pragma once
#include <iostream>
#include <ctime>
#include <ratio>
#include <chrono>
#include <limits>
#include <array>
using std::cout;
using std::endl;
using std::cin;

void whyForLoop();
void descForLoop();
void oddNumberRange();
void oddNumberRangeDesc();
void guessOutput();
void printEvenNumbersLessThanN();
void printFirstNEvenNumbers();
int get_positive_integer();
int exitDemo();